name: Docker Image Build and Deploy

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/dipayan90/${GITHUB_REPOSITORY}:${GITHUB_SHA} --tag docker.pkg.github.com/dipayan90/${GITHUB_REPOSITORY}:latest
    - name: Login to Github docker Registry
      run: docker login docker.pkg.github.com --username dipayan90 --password ${GITHUB_PASSWORD}
    - name: Push Image To Registry
      run: docker push docker.pkg.github.com/dipayan90/${GITHUB_REPOSITORY}:${GITHUB_SHA} && docker push docker.pkg.github.com/dipayan90/${GITHUB_REPOSITORY}:latest